version: "3.8"

services:
  node:
    build:
      context: ./
      dockerfile: ./xpn-dockerfile
    image: expand
    privileged: true
    volumes:
      - type: bind
        source: .
        target: /work
      - type: bind
        source: ./export
        target: /nfs
    networks:
      - backend

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.0.0/16