
networks:
  b0:
    driver: bridge

services:
  node:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: expandfs/xpn-docker
    volumes:
      - type: bind
        source: ..
        target: /work
      - type: bind
        source: ../export
        target: /export
      - type: bind
        source: /lib/modules
        target: /lib/modules
      - type: bind
        source: ..
        target: /shared
      - type: bind
        source: /nvme
        target: /storage_local
      - type: bind
        source: /dev/shm
        target: /storage_shm
      - type: bind
        source: ..
        target: /storage_backend
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - b0
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    privileged: true
    cap_add:
      - ALL

volumes:
  shared:

