name: xpn-docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker image build --no-cache -t xpn-docker --build-arg UID=$(id -u) --build-arg GID=$(id -g) -f docker/dockerfile .

