
name: XPN Docker workflow CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-xpn-docker:    
    name: Build xpn Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU        
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:qemu-v7.0.0-28
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Package Registry        
      run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Checkout
      uses: actions/checkout@v4  
    - name: Build & Push Docker image
      run:  docker buildx build --platform=linux/amd64,linux/arm64 --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t ghcr.io/${{ github.repository_owner }}/xpn-docker:${GITHUB_SHA} -t ghcr.io/${{ github.repository_owner }}/xpn-docker -f ./docker/dockerfile  --push .

  push-xpn-docker:    
    name: Push XPN Docker Image
    needs: build-xpn-docker
    if: github.repository == 'xpn-arcos/xpn-docker'
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub        
      env:          
        DH_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}               
      run: docker login -u expandfs -p ${DH_TOKEN}
    - name: Re-tag & Push Docker Image to Docker Hub        
      run: |          
        chmod +r $HOME/.docker/config.json
        docker container run --rm --network host -v regctl-conf:/home/appuser/.regctl/ -v $HOME/.docker/config.json:/home/appuser/.docker/config.json regclient/regctl:v0.3.9 image copy ghcr.io/${{ github.repository_owner }}/xpn-docker:${GITHUB_SHA}  docker.io/expandfs/xpn-docker:${GITHUB_SHA}
        docker container run --rm --network host -v regctl-conf:/home/appuser/.regctl/ -v $HOME/.docker/config.json:/home/appuser/.docker/config.json regclient/regctl:v0.3.9 image copy ghcr.io/${{ github.repository_owner }}/xpn-docker docker.io/expandfs/xpn-docker
    
